force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <label>Picklist</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Dependency__c/Picklist_Dependency__c.object-meta.xml
<CustomObject>
    <label>Picklist Dependency</label>
    <nameField>
        <label>Picklist Dependency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Dependency_Value__c/Picklist_Dependency_Value__c.object-meta.xml
<CustomObject>
    <label>Picklist Dependency Value</label>
    <nameField>
        <displayFormat>PDV-{000000}</displayFormat>
        <label>Picklist Dependency Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Dependency Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Dependency_Value__c/fields/Picklist_Dependency__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Dependency__c</fullName>
    <label>Picklist Dependency</label>
    <referenceTo>Picklist_Dependency__c</referenceTo>
    <relationshipLabel>Picklist Dependency Values</relationshipLabel>
    <relationshipName>Picklist_Dependency_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Field__c/Picklist_Field__c.object-meta.xml
<CustomObject>
    <label>Picklist Field</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Picklist Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Field__c/fields/Field_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Developer_Name__c</fullName>
    <label>Field Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Field__c/fields/Object_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Developer_Name__c</fullName>
    <label>Object Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Field__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Fields</relationshipLabel>
    <relationshipName>Picklist_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Value__c/Picklist_Value__c.object-meta.xml
<CustomObject>
    <label>Picklist Value</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Picklist Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Value__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Values</relationshipLabel>
    <relationshipName>Picklist_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PicklistsManagerQueueable.cls
public class PicklistsManagerQueueable implements Queueable, Database.AllowsCallouts {

    private Id recordId;

    /* Variables for deploy Picklist__c */
    private Map<String, Picklist_Value__c> picklistValuesToInsert;
    private List<Picklist_Field__c> picklistFields;

    /* Variables for deploy Picklist_Dependency__c */
    private Picklist_Dependency__c pd;
    private List<Picklist_Dependency_Value__c> pdvs;

    /* Constructor for deploy Picklist__c */
    public PicklistsManagerQueueable(Id recordId, Map<String, Picklist_Value__c> picklistValuesToInsert, List<Picklist_Field__c> picklistFields){
        this.recordId = recordId;
        this.picklistValuesToInsert = picklistValuesToInsert;
        this.picklistFields = picklistFields;
    }

    /* Constructor for deploy Picklist_Dependency__c */
    public PicklistsManagerQueueable(Id recordId, Picklist_Dependency__c pd, List<Picklist_Dependency_Value__c> pdvs){
        this.recordId = recordId;
        this.pd = pd;
        this.pdvs = pdvs;
    }

    public void execute(QueueableContext context) {

        if(recordId.getSobjectType() == Schema.Picklist__c.SObjectType) {
            PicklistsManagerUtils.updateValueSet(picklistValuesToInsert, picklistFields.get(0).Object_Developer_Name__c, picklistFields.get(0).Field_Developer_Name__c);
            if(picklistFields.size() > 1) {
                picklistFields.remove(0);
                System.enqueueJob(new PicklistsManagerQueueable(recordId, picklistValuesToInsert, picklistFields));
            }
        }
        else if(recordId.getSobjectType() == Schema.Picklist_Dependency__c.SObjectType) {
            PicklistsManagerUtils.updatePicklistDependency(pd, pdvs);
        }


        
    }
}